name: automationTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        next-version: [13.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: install and run tests
        run: |
         cd frontend
         npm ci
         npx jest


     
          
        
